### ISSUE TITLE
Style: Broken UUID Links -> Normal Text

### ISSUE THREAD

**Issue by Algor0113** [MetaMorphic-Digital/torgeternity#382]
Refering to Drental, it's possible. I'll look through that!

**Comment by Drental** [comment]
```scss
a.entity-link,
a.content-link,
a.inline-roll {
  &.broken {
    color: inherit;
    text-decoration: inherit;
    cursor: text;

    &:hover {
      text-shadow: none;
    }
  }
}
```
might need de-scssification

**Comment by Drental** [comment]
```css
a.entity-link.broken,
a.content-link.broken,
a.inline-roll.broken {
	 color: inherit;
	 text-decoration: inherit;
	 cursor: text;
}
a.entity-link.broken:hover,
a.content-link.broken:hover,
a.inline-roll.broken:hover {
	 text-shadow: none;
}
```
